alias shutdown='sudo shutdown -h now'
alias ls='ls --color=auto'
alias ll='ls -l --color=auto'
alias la='ls -a --color=auto'
alias lla='ls -la --color=auto'
alias less='less --quiet'
alias h='cd ~'
alias x='startx'
alias grep='grep --color=auto'
alias dmesg='dmesg -H'
alias qq='exit'
alias df='df -h'
alias su='su -l'
alias kill='tmux kill-session -t'
alias cleansys='sudo pacman -Rscn $(pacman -Qdtq)'
#
alias lss='ls --color=never'
