alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias ls='ls --classify --color=auto --human-readable'
alias nls='ls --classify --color=never --human-readable'
alias ll='ls -l'
alias ll='ls -l'
alias hdd1='cd /mnt/HDD1'
alias less='less --quiet'
alias h='cd ~'
alias grep='grep --color=auto'
alias dmesg='dmesg -H'
alias q='exit'
alias df='df --human-readable'
alias su='su -l'
alias paclog='tail -n 40 /var/log/pacman.log'
alias off='sudo shutdown -h now'
alias kill='tmux kill-session -t'
alias x='startx'
alias c='clear'
alias cleansys='sudo pacman -Rscn $(pacman -Qdtq)'
alias hdd1='cd /mnt/HDD1'
alias hdd2='cd /mnt/HDD2'
alias copy='rsync -a --info=stats1,progress2'

